### ISSUE TITLE
Resource NullReferenceException

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#316]
#### Summary

Get a null_reference_exception, when you renamed a resource (class), that was attached to another gameobject.
On top of that the hole project will explode. (It's empty)

#### How to reproduce

- Create a resource
- Attach it to a gameobject
- Rename the class of the resource.

#### Workaround

- Nope

#### Attachments

``````
Application: DualityEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Duality.Resource.GetTypeByFileName(System.String)
   at Duality.ContentRef`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_ResType()
   at Duality.Editor.HelpInfo.FromResource(Duality.IContentRef)
   at Duality.Editor.Plugins.ProjectView.ProjectFolderView.Duality.Editor.IHelpProvider.ProvideHoverHelp(System.Drawing.Point, Boolean ByRef)
   at Duality.Editor.HelpSystem.UpdateHelpStack()
   at Duality.Editor.HelpSystem.DualityEditorApp_EventLoopIdling(System.Object, System.EventArgs)
   at Duality.Editor.DualityEditorApp.OnEventLoopIdling()
   at Duality.Editor.DualityEditorApp.Application_Idle(System.Object, System.EventArgs)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at Duality.Editor.Program.Main(System.String[])
``````

**Comment by ilexp** [comment]
#### Workaround

Implement a custom SerializeErrorHandler ([example](https://github.com/AdamsLair/duality/blob/master/DualityPlugins/Compatibility/MovedTypesV2ErrorHandler.cs)) to allow the editor to locate your renamed type.

------

Thanks for reporting. Probably just a forgotten null reference check.

**Comment by ilexp** [comment]
Fixed. Will be deployed with the next binary release.
