### ISSUE TITLE
Exception by adding vertices to a shape

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#317]
#### Summary

The editor throws an exception, when you try to add vertices to a shape in the object inspector.

#### How to reproduce 

1. Create a custom component
2. Add a property 'PolyShapeInfo' to the component.

``
public PolyShapeInfo Shape { get; set; } = new PolyShapeInfo();
``
3. Try to add vertices in the object inspector.

#### Workaround

- Nope

#### Attachments

- The Exception:

``````````````````````````````````
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Editor.Plugins.Base.PropertyEditors.RigidBodyShapePropertyEditor.OnPropertySet(PropertyInfo property, IEnumerable`1 targets)
   at AdamsLair.WinForms.PropertyEditing.MemberwisePropertyEditor.<>c__DisplayClass24.<CreatePropertyValueSetter>b__23(IEnumerable`1 values) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\MemberwisePropertyEditor.cs:line 416
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.SetValues(IEnumerable`1 objEnum) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 456
   at AdamsLair.WinForms.PropertyEditing.Editors.IListPropertyEditor.OnButtonPressed() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditors\IListPropertyEditor.cs:line 319
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.OnMouseUp(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 670
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseUp(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 788
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseUp(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 792
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseUp(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 792
   at AdamsLair.WinForms.PropertyEditing.PropertyGrid.OnMouseUp(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyGrid.cs:line 722
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
``````````````````````````````````

**Comment by ilexp** [comment]
Thanks for reporting! Same as with the other bug, probably just a forgotten null reference check. 

That said, shape info objects are not actually intended to be put into a variable and edited in the inspector independently of a RigidBody they belong to. So while this is technically a bug and you shouldn't run into this, please also consider taking a different approach as a workaround.

**Comment by ilexp** [comment]
Fixed. Will be deployed with the next binary release.
