### ISSUE TITLE
Provide Proper Error Messages When Using Multi-Dimensional Arrays

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#337]
#### Summary

Duality throws an InvalidCastException, when you create a byte array in a component:

`private byte[,] tiles = new byte[16, 16];
`
#### Attachments

Exception:

```
[Edit] Error:   An error occurred: InvalidCastException: Unable to cast object of type 'System.Byte[]' to type 'System.Byte[,]'.
CallStack:
   at Duality.Cloning.CloneProvider.Duality.Cloning.ICloneOperation.HandleObject[T](T source, T& target) in c:\projects\duality\Duality\Cloning\CloneProvider.cs:line 837
   at Duality.Cloning.CloneProvider.PerformCopyChildObject(Object source, Object target, CloneType typeData) in c:\projects\duality\Duality\Cloning\CloneProvider.cs:line 602
   at Duality.Cloning.CloneProvider.Duality.Cloning.ICloneOperation.HandleObject[T](T source, T& target) in c:\projects\duality\Duality\Cloning\CloneProvider.cs:line 814
   at Duality.Cloning.ExtMethodsICloneOperation.HandleObject[T](ICloneOperation operation, T source, T target) in c:\projects\duality\Duality\Cloning\ICloneOperation.cs:line 22
   at Duality.Cloning.CloneProvider.PerformCopyObject(Object source, Object target, CloneType typeData) in c:\projects\duality\Duality\Cloning\CloneProvider.cs:line 518
   at Duality.Cloning.CloneProvider.CloneObject[T](T source, Boolean preserveCache) in c:\projects\duality\Duality\Cloning\CloneProvider.cs:line 130
   at Duality.Editor.UndoRedoActions.CreateComponentAction.<Do>b__0(Component o) in c:\projects\duality\DualityEditor\UndoRedoActions\CreateComponentAction.cs:line 47
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Duality.Editor.UndoRedoActions.CreateComponentAction.Do() in c:\projects\duality\DualityEditor\UndoRedoActions\CreateComponentAction.cs:line 47
   at Duality.Editor.Plugins.SceneView.SceneView.CreateComponent(TreeNodeAdv baseNode, Type cmpType) in c:\projects\duality\DualityEditorPlugins\SceneView\Modules\SceneView.cs:line 511
   at Duality.Editor.Plugins.SceneView.SceneView.newToolStripMenuItem_ItemClicked(Object sender, EventArgs e) in c:\projects\duality\DualityEditorPlugins\SceneView\Modules\SceneView.cs:line 1528
   at AdamsLair.WinForms.ItemModels.MenuModelItem.RaisePerformAction() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\ItemModels\MenuModelItem.cs:line 318
   at AdamsLair.WinForms.ItemViews.MenuStripMenuView.viewMenuItem_Click(Object sender, EventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\ItemViews\MenuStripMenuView.cs:line 306
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by ilexp** [comment]
Multi-dimensional arrays are not supported by Duality. Use single-dimensional arrays instead. In some cases, you may also find the `Grid<T>` class useful.

This is still a bug in the sense that there should be proper error handling and a descriptive message though.

**Comment by Barsonax** [comment]
I will look into this one

**Comment by ilexp** [comment]
👍

**Comment by Barsonax** [comment]
See PR #580

**Comment by ilexp** [comment]
Done in the above PR.
