### ISSUE TITLE
NullReferenceException when creating a new project

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#361]
I've got an NullReferenceException, when I created a new project.

I just played with the new tilemap features.

The Stacktrace:

```
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.IO.FileOp.Exists(String path) in c:\projects\duality\Duality\IO\FileOp.cs:line 21
   at Duality.ContentProvider.LoadContent(String path) in c:\projects\duality\Duality\ContentProvider.cs:line 444
   at Duality.ContentProvider.RequestContent[T](String path) in c:\projects\duality\Duality\ContentProvider.cs:line 398
   at Duality.ContentRef`1.RetrieveInstance() in c:\projects\duality\Duality\ContentRef.cs:line 259
   at Duality.ContentRef`1.get_Res() in c:\projects\duality\Duality\ContentRef.cs:line 41
   at Duality.Editor.Plugins.Tilemaps.TilesetEditorModes.VisualLayerTilesetEditorMode.OnLayerSelectionChanged(LayerSelectionChangedEventArgs args) in c:\projects\duality\DualityEditorPlugins\Tilemaps\TilesetEditorModes\VisualLayerTilesetEditorMode.cs:line 224
   at Duality.Editor.Plugins.Tilemaps.TilesetEditor.layerView_SelectionChanged(Object sender, EventArgs e) in c:\projects\duality\DualityEditorPlugins\Tilemaps\Modules\TilesetEditor.cs:line 391
   at Aga.Controls.Tree.TreeViewAdv.OnSelectionChanged() in c:\Stuff\svn\Projects\AdamsLair.TreeViewAdv\Aga.Controls\Tree\TreeViewAdv.cs:line 114
   at Aga.Controls.Tree.TreeViewAdv.EndUpdate() in c:\Stuff\svn\Projects\AdamsLair.TreeViewAdv\Aga.Controls\Tree\TreeViewAdv.cs:line 363
   at Aga.Controls.Tree.TreeViewAdv.set_SelectedNode(TreeNodeAdv value) in c:\Stuff\svn\Projects\AdamsLair.TreeViewAdv\Aga.Controls\Tree\TreeViewAdv.Properties.cs:line 777
   at Duality.Editor.Plugins.Tilemaps.TilesetEditor.SetActiveEditorMode(TilesetEditorMode mode) in c:\projects\duality\DualityEditorPlugins\Tilemaps\Modules\TilesetEditor.cs:line 85
   at Duality.Editor.Plugins.Tilemaps.TilesetEditor.OnClosed(EventArgs e) in c:\projects\duality\DualityEditorPlugins\Tilemaps\Modules\TilesetEditor.cs:line 267
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

````

**Comment by ilexp** [comment]
Thanks for reporting! Will have a look tomorrow.

**Comment by ilexp** [comment]
Fixed. Release in progress, will be available in around 20 minutes.
