### ISSUE TITLE
Define the maximum size of lists to avoid an OutOfMemoryException in the propertyeditor

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#397]
When you create a new List<T> in the PropertyEditor and set the size of the list to an unusual size (e.g. 20023), the editor throws an OutOfMemoryException.

StackTrace:
`````
[Edit] Error:   An error occurred: OutOfMemoryException: Array dimensions exceeded supported range.
CallStack:
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at AdamsLair.WinForms.PropertyEditing.Editors.IListPropertyEditor.SizeValueSetter(IEnumerable`1 values) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditors\IListPropertyEditor.cs:line 237
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.SetValues(IEnumerable`1 objEnum) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 465
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.PerformSetValue() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 436
   at AdamsLair.WinForms.PropertyEditing.Editors.NumericPropertyEditor.numEditor_Edited(Object sender, EventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditors\NumericPropertyEditor.cs:line 261
   at AdamsLair.WinForms.PropertyEditing.Templates.EditorTemplate.EmitEdited(Object value) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\EditorTemplate.cs:line 94
   at AdamsLair.WinForms.PropertyEditing.Templates.NumericEditorTemplate.stringEditor_Edited(Object sender, EventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\NumericEditorTemplate.cs:line 418
   at AdamsLair.WinForms.PropertyEditing.Templates.EditorTemplate.EmitEdited(Object value) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\EditorTemplate.cs:line 94
   at AdamsLair.WinForms.PropertyEditing.Templates.StringEditorTemplate.InsertText(String insertText) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\StringEditorTemplate.cs:line 130
   at AdamsLair.WinForms.PropertyEditing.Templates.StringEditorTemplate.OnKeyPress(KeyPressEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\StringEditorTemplate.cs:line 218
   at AdamsLair.WinForms.PropertyEditing.Templates.NumericEditorTemplate.OnKeyPress(KeyPressEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\NumericEditorTemplate.cs:line 228
   at AdamsLair.WinForms.PropertyEditing.PropertyGrid.OnKeyPress(KeyPressEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyGrid.cs:line 887
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
````

Peace out! :v:

**Comment by ilexp** [comment]
Done. Binary release in progress, check back for package updates in about 30 minutes.
