### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#399]
Hello!
Here are two bugs that I found:

I found them yesterday, so I don't know exactly what I've done. So.. jeah, I just wrote them down...😄 

```
 [Core] Error:       Error reading object: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Serialization.XmlSerializer.ReadArray(XElement element, ObjectHeader header) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 496
   at Duality.Serialization.XmlSerializer.ReadObjectBody(XElement element, ObjectHeader header) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 464
   at Duality.Serialization.XmlSerializer.ReadObjectData(XElement element) in c:\projects\duality\Duality\Serialization\XmlSerializer.cs:line 446
```

The other one:

```
[Edit] Error:   An error occurred: TargetInvocationException: Exception has been thrown by the target of an invocation.
CallStack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at AdamsLair.WinForms.PropertyEditing.MemberwisePropertyEditor.<>c__DisplayClass1d.<CreatePropertyValueGetter>b__1c(Object o) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\MemberwisePropertyEditor.cs:line 397
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Duality.Editor.Controls.PropertyEditors.Vector2PropertyEditor.OnGetValue() in c:\projects\duality\DualityEditor\Controls\PropertyEditors\Vector2PropertyEditor.cs:line 29
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.PerformGetValue() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 430
   at AdamsLair.WinForms.PropertyEditing.MemberwisePropertyEditor.OnGetValue() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\MemberwisePropertyEditor.cs:line 286
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.PerformGetValue() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 430
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.set_Expanded(Boolean value) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 63
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 775
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 752
   at AdamsLair.WinForms.PropertyEditing.PropertyGrid.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyGrid.cs:line 700
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by ilexp** [comment]
Fixed the first one (Release in progress, check for updates in about 30 minutes), but the second one is potentially caused by your own code. What's happening is that the Inspector attempted to read out a property of one of your Components, but unfortunately, that property getter threw an exception. You might need to fix that property getter implementation.

If it turns out that the property in question is one of Duality's, please do report back with another issue!
