### ISSUE TITLE
NullReferenceException when deleting the Texture of a Tilemap

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#404]
Create a new TileMap with the TileMap-Plugin and delete the Texture, that are you using for the tilemap.

The editor will throw this exception and the GDI-Stuff will break:

```
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Plugins.Tilemaps.Tileset.LookupTileSourceRect(Int32 renderConfigIndex, Int32 tileIndex, Point2& pos, Point2& size) in c:\projects\duality\DualityPlugins\Tilemaps\Tilesets\Tileset.cs:line 191
   at Duality.Editor.Plugins.Tilemaps.TilesetView.OnPaintTiles(PaintEventArgs e) in c:\projects\duality\DualityEditorPlugins\Tilemaps\Modules\TilesetView.cs:line 747
   at Duality.Editor.Plugins.Tilemaps.SourcePaletteTilesetView.OnPaintTiles(PaintEventArgs e) in c:\projects\duality\DualityEditorPlugins\Tilemaps\Modules\SourcePaletteTilesetView.cs:line 129
   at Duality.Editor.Plugins.Tilemaps.TilesetView.OnPaint(PaintEventArgs e) in c:\projects\duality\DualityEditorPlugins\Tilemaps\Modules\TilesetView.cs:line 908
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

![c89pd2a](https://cloud.githubusercontent.com/assets/6233308/19017656/a9de443a-8842-11e6-9cfa-0be018514f5b.png)

**Comment by ilexp** [comment]
Thanks for reporting! Definitely a bug in the Tilemaps core plugin.

**Comment by ilexp** [comment]
Put this up for grabs, but this will require some deeper investigation. If anyone's up for it, let me know. Otherwise, I'll look into it sooner or later.
