### ISSUE TITLE
Exception When Running a Temporary Scene in the Sandbox and Hot-Reloading Core Plugins

### ISSUE THREAD

**Issue by ilexp** [AdamsLair/duality#421]
### Summary

When hot-reloading core plugins while running the Sandbox mode in a Scene that has never been saved anywhere, there will be an exception when leaving Sandbox mode due to an attempt to return to a (now destroyed) temporary Scene.

### Attachments

```
[Edit] ERR: An error occurred: ArgumentException: Can't switch to Scene '' because it doesn't seem to exist.
            Parameter name: scene
            CallStack:
               at Duality.Resources.Scene.SwitchTo(ContentRef`1 scene, Boolean forceImmediately) in c:\Stuff\svn\Projects\Duality\master\Duality\Resources\Scene.cs:line 155
               at Duality.Editor.Sandbox.Stop() in c:\Stuff\svn\Projects\Duality\master\DualityEditor\Sandbox.cs:line 158
               at Duality.Editor.Forms.MainForm.actionStopSandbox_Click(Object sender, EventArgs e) in c:\Stuff\svn\Projects\Duality\master\DualityEditor\Forms\MainForm.cs:line 585
               at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
               at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
               at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
               at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
               at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
               at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
               at System.Windows.Forms.Control.WndProc(Message& m)
               at System.Windows.Forms.ToolStrip.WndProc(Message& m)
               at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by ilexp** [comment]
Done.
