### ISSUE TITLE
Tilemap: NullReferenceException after deleting the tileset

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#430]
I've got an NullReferenceException after I deleted the tileset of a map in the sceneview.

The Map-Gameobject was already added and filled with tiles.

````
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Plugins.Tilemaps.TilemapCollider.GetRawTileData(Tilemap[] tilemaps) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 467
   at Duality.Plugins.Tilemaps.TilemapCollider.MergeCollisionData(Int32 sectorX, Int32 sectorY, Grid`1 target) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 268
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 211
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY, Int32 sectorCountX, Int32 sectorCountY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 201
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(Boolean rebuildEvenIfUnchanged) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 188
   at Duality.Plugins.Tilemaps.TilemapCollider.Duality.ICmpInitializable.OnInit(InitContext context) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 380
   at Duality.GameObject.IterateComponents[T](Action`1 forEach, Predicate`1 where) in c:\projects\duality\Duality\GameObject.cs:line 675
   at Duality.Resources.Scene.<OnEntered>b__2() in c:\projects\duality\Duality\Resources\Scene.cs:line 264
   at Duality.DualityApp.EditorGuard(Action action) in c:\projects\duality\Duality\DualityApp.cs:line 983
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Plugins.Tilemaps.TilemapCollider.GetRawTileData(Tilemap[] tilemaps) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 467
   at Duality.Plugins.Tilemaps.TilemapCollider.MergeCollisionData(Int32 sectorX, Int32 sectorY, Grid`1 target) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 268
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 211
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY, Int32 sectorCountX, Int32 sectorCountY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 201
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(Boolean rebuildEvenIfUnchanged) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 188
   at Duality.Plugins.Tilemaps.TilemapCollider.Duality.ICmpInitializable.OnInit(InitContext context) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 380
   at Duality.GameObject.IterateComponents[T](Action`1 forEach, Predicate`1 where) in c:\projects\duality\Duality\GameObject.cs:line 675
   at Duality.Resources.Scene.<OnEntered>b__2() in c:\projects\duality\Duality\Resources\Scene.cs:line 264
   at Duality.DualityApp.EditorGuard(Action action) in c:\projects\duality\Duality\DualityApp.cs:line 983
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Plugins.Tilemaps.TilemapCollider.GetRawTileData(Tilemap[] tilemaps) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 467
   at Duality.Plugins.Tilemaps.TilemapCollider.MergeCollisionData(Int32 sectorX, Int32 sectorY, Grid`1 target) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 268
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 211
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY, Int32 sectorCountX, Int32 sectorCountY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 201
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(Boolean rebuildEvenIfUnchanged) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 188
   at Duality.Plugins.Tilemaps.TilemapCollider.Duality.ICmpInitializable.OnInit(InitContext context) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 380
   at Duality.GameObject.IterateComponents[T](Action`1 forEach, Predicate`1 where) in c:\projects\duality\Duality\GameObject.cs:line 675
   at Duality.Resources.Scene.<OnEntered>b__2() in c:\projects\duality\Duality\Resources\Scene.cs:line 264
   at Duality.DualityApp.EditorGuard(Action action) in c:\projects\duality\Duality\DualityApp.cs:line 983
[Core] Info:    Loading Resource 'Data\Scenes\Levels\TestLevel.Scene.res'
[Core] Info:    Loading Resource 'Data\Scenes\Levels\TestLevel.Scene.res'
[Core] Info:    Loading Resource 'Data\Scenes\Levels\TestLevel.Scene.res'
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Plugins.Tilemaps.TilemapCollider.GetRawTileData(Tilemap[] tilemaps) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 467
   at Duality.Plugins.Tilemaps.TilemapCollider.MergeCollisionData(Int32 sectorX, Int32 sectorY, Grid`1 target) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 268
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 211
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY, Int32 sectorCountX, Int32 sectorCountY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 201
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(Boolean rebuildEvenIfUnchanged) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 188
   at Duality.Plugins.Tilemaps.TilemapCollider.Duality.ICmpInitializable.OnInit(InitContext context) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 380
   at Duality.GameObject.IterateComponents[T](Action`1 forEach, Predicate`1 where) in c:\projects\duality\Duality\GameObject.cs:line 675
   at Duality.Resources.Scene.<OnEntered>b__2() in c:\projects\duality\Duality\Resources\Scene.cs:line 264
   at Duality.DualityApp.EditorGuard(Action action) in c:\projects\duality\Duality\DualityApp.cs:line 983
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Plugins.Tilemaps.TilemapCollider.GetRawTileData(Tilemap[] tilemaps) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 467
   at Duality.Plugins.Tilemaps.TilemapCollider.MergeCollisionData(Int32 sectorX, Int32 sectorY, Grid`1 target) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 268
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 211
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY, Int32 sectorCountX, Int32 sectorCountY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 201
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(Boolean rebuildEvenIfUnchanged) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 188
   at Duality.Plugins.Tilemaps.TilemapCollider.Duality.ICmpInitializable.OnInit(InitContext context) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 380
   at Duality.GameObject.IterateComponents[T](Action`1 forEach, Predicate`1 where) in c:\projects\duality\Duality\GameObject.cs:line 675
   at Duality.Resources.Scene.<OnEntered>b__2() in c:\projects\duality\Duality\Resources\Scene.cs:line 264
   at Duality.DualityApp.EditorGuard(Action action) in c:\projects\duality\Duality\DualityApp.cs:line 983
[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Plugins.Tilemaps.TilemapCollider.GetRawTileData(Tilemap[] tilemaps) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 467
   at Duality.Plugins.Tilemaps.TilemapCollider.MergeCollisionData(Int32 sectorX, Int32 sectorY, Grid`1 target) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 268
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 211
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(RigidBody body, Int32 sectorX, Int32 sectorY, Int32 sectorCountX, Int32 sectorCountY) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 201
   at Duality.Plugins.Tilemaps.TilemapCollider.UpdateRigidBody(Boolean rebuildEvenIfUnchanged) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 188
   at Duality.Plugins.Tilemaps.TilemapCollider.Duality.ICmpInitializable.OnInit(InitContext context) in c:\projects\duality\DualityPlugins\Tilemaps\Tilemaps\Components\TilemapCollider.cs:line 380
   at Duality.GameObject.IterateComponents[T](Action`1 forEach, Predicate`1 where) in c:\projects\duality\Duality\GameObject.cs:line 675
   at Duality.Resources.Scene.<OnEntered>b__2() in c:\projects\duality\Duality\Resources\Scene.cs:line 264
   at Duality.DualityApp.EditorGuard(Action action) in c:\projects\duality\Duality\DualityApp.cs:line 983

[Edit] Error:   An error occurred: NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Editor.Plugins.CamView.CamViewStates.RigidBodyEditorCamViewState.BeginToolAction(RigidBodyEditorTool action) in c:\projects\duality\DualityEditorPlugins\CamView\CamViewStates\RigidBodyEditor\RigidBodyEditorCamViewState.cs:line 424
   at Duality.Editor.Plugins.CamView.CamViewStates.CamViewState.RenderableControl_MouseDown(Object sender, MouseEventArgs e) in c:\projects\duality\DualityEditorPlugins\CamView\CamViewStates\CamViewState.cs:line 775
   at System.Windows.Forms.MouseEventHandler.Invoke(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

````

**Comment by ilexp** [comment]
Fixed and release in progress. Check for package updates in about 30 minutes.
