### ISSUE TITLE
Running Duality for the first time without internet access causes a crash.

### ISSUE THREAD

**Issue by hsnabn** [AdamsLair/duality#465]
### Summary

A fresh Duality binary (no packages installed), when run without internet access, crashes with a `NullReferenceException` when the license agreement is accepted. The same result occurs when Duality is blocked in the firewall.

Bug reported by user **misthema** on Discord server.

### How to reproduce

- Turn off internet access, or block Duality in the firewall (this might be done by default on some systems?).
- Run a fresh Duality binary install (downloaded from http://dualitybin.adamslair.net).
- Accept license agreement.

### Possible solutions

- Some sort of handling for cases where internet access is unavailable.

### Attachments

- logfile_editor.txt:
```
[Edit] Msg: Updating Packages...
[Edit] ERR:   Failed to perform task: NullReferenceException: Object reference not set to an instance of an object.
              CallStack:
                 at Duality.Editor.PackageManagement.PackageManager.GetDeepDependencyCount(IEnumerable`1 packages)
                 at Duality.Editor.PackageManagement.PackageManager.OrderByDependencies(IList`1 packages)
                 at Duality.Editor.PackageManagement.PackageManager.OrderByDependencies(IList`1 packages)
                 at Duality.Editor.Program.<FirstTimeSetup>d__1.MoveNext()
                 at Duality.Editor.Forms.ProcessingBigTaskDialog.WorkerThreadProc(Object args)
[Edit] ERR: An error occurred: FileNotFoundException: Could not load file or assembly 'AdamsLair.WinForms, Version=1.0.16.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
            CallStack:
               at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
               at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
               at Duality.Editor.Forms.SplashScreen.mainFormLoader_DoWork(Object sender, DoWorkEventArgs e)
               at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
               at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by ilexp** [comment]
Thanks for reporting! Nice issue description 👍 That's definitely a usability bug, should catch this case and add a proper error dialog on this.

**Comment by hsnabn** [comment]
Also, might I add, the license itself does not actually display in this case.

Maybe in cases where the license was not retrieved, display a link to the license with some kind of message?

**Comment by ilexp** [comment]
> Maybe in cases where the license was not able to be retrieved, display a link to the license with some kind of message?

This should already be the case. There's code that does that. Should check this when dealing with this issue.

**Comment by hsnabn** [comment]
Ah, yes, sorry, false alarm.

**Comment by ilexp** [comment]
Fixed, and binaries have been released. Fixed some internal exceptions, and there should now be an info dialog if the first install fails.
