### ISSUE TITLE
Check if enough file space is available while downloading packages

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#486]
### Summary

I tried to install Duality on an other computer. DualityEditor crashed because I hadn't enough file space on this computer.

The eventviewer displays this stacktrace:

````
Application: DualityEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileFormatException
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(System.IO.Stream, System.IO.FileMode, System.IO.FileAccess, Boolean)
   at System.IO.Packaging.ZipPackage..ctor(System.IO.Stream, System.IO.FileMode, System.IO.FileAccess, Boolean)
   at System.IO.Packaging.Package.Open(System.IO.Stream, System.IO.FileMode, System.IO.FileAccess, Boolean)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.LocalPackageRepository.OpenPackage(System.String)

Exception Info: System.IO.InvalidDataException
   at NuGet.LocalPackageRepository.OpenPackage(System.String)
   at NuGet.LocalPackageRepository.GetPackage(System.Func`2<System.String,NuGet.IPackage>, System.String)
   at System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToArray[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at Duality.Editor.PackageManagement.PackageManager.get_IsPackageSyncRequired()
   at Duality.Editor.Program.Main(System.String[])
````

**Comment by ilexp** [comment]
Looks like we should check whether the available space on the drive that Duality is about to install packages to is bigger than the size requirements by both package and its dependencies.

**Comment by bc2026** [comment]
Is this resolved?
