### ISSUE TITLE
Object Inspector crashes when gameobjects have null string as name

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#505]
### Summary
The Object Inspector crashes when you create a new gameobject by code and assign a null string as the name of the gameobject.

### How to reproduce
Create a new GameObject with a null string as name (code)

### Attachments

**Screenshot**
![](http://i.imgur.com/PUPLlG2.png)

**Log**
````
[Edit] Error:       NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at Duality.Editor.Plugins.Base.PropertyEditors.GameObjectPropertyEditor.OnPaint(PaintEventArgs e) in c:\projects\duality\Source\Plugins\EditorBase\PropertyEditors\GameObjectPropertyEditor.cs:line 196
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnPaint(PaintEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 603
   at AdamsLair.WinForms.PropertyEditing.PropertyGrid.OnPaint(PaintEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyGrid.cs:line 605
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
````

**Comment by ilexp** [comment]
Thanks for reporting! 

Putting this up for grabs, as it shouldn't be too big of a deal in case someone is interested in contributing on this: Create a test case to reproduce the problem. Identify the spot that doesn't deal with null names. Change it so it handles the case accordingly and uses "null" as a string instead, when the reference is actually null.

Whether or not GameObject names should be allowed to be null is a different question, but this is for another day and not within the scope of this issue.

**Comment by ilexp** [comment]
Fixed by @ividito, pending binary release.
