### ISSUE TITLE
Duality Editor crashes in VM

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#516]
### Summary

I'm on a linux machine (Linux Mint 18) and set up Windows 10 in virtual box.
(3D acceleration is enabled)

As soon as I start Duality Editor, it crashes. 
This shows me the event viewer of windows:
```
Application: DualityEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL+Ext.GenFramebuffers(Int32, Int32 ByRef)
   at Duality.Backend.DefaultOpenTK.NativeRenderTarget.Duality.Backend.INativeRenderTarget.Setup(System.Collections.Generic.IReadOnlyList`1<Duality.Backend.INativeTexture>, Duality.AAQuality)
   at Duality.Resources.RenderTarget.SetupNativeRes()
   at Duality.Resources.RenderTarget..ctor(Duality.AAQuality, Duality.ContentRef`1<Duality.Resources.Texture>[])
   at Duality.Components.Camera.SetupPickingRT(Duality.Point2)
   at Duality.Components.Camera.RenderPickingMap(Duality.Point2, Boolean)
   at Duality.Editor.Plugins.CamView.CamViewClient.RenderPickingMap()
   at Duality.Editor.Plugins.CamView.CamViewClient.PickRendererAt(Int32, Int32)
   at Duality.Editor.Plugins.CamView.CamViewStates.SceneEditorCamViewState.PickSelObjAt(Int32, Int32)
   at Duality.Editor.Plugins.CamView.CamViewStates.ObjectEditorCamViewState.UpdateMouseover(System.Drawing.Point)
   at Duality.Editor.Plugins.CamView.CamViewStates.ObjectEditorCamViewState.UpdateAction()
   at Duality.Editor.Plugins.CamView.CamViewStates.SceneEditorCamViewState.ApplyEditorSelection(Duality.Editor.ObjectSelection)
   at Duality.Editor.Plugins.CamView.CamView.SetCurrentState(Duality.Editor.Plugins.CamView.CamViewStates.CamViewState)
   at Duality.Editor.Plugins.CamView.CamView.OnShown(System.EventArgs)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at Duality.Editor.Program.Main(System.String[])
```
I can run the Duality Launcher without any problems...

**Comment by ilexp** [comment]
An `AccessViolationException` on accessing an OpenGL feature is a telltale sign of a required OpenGL feature not being available on that system. Can you share the full logfile of either launcher or editor?

**Comment by hsnabn** [comment]
I noticed you say you used VirtualBox? It seems VirtualBox does not support physical GPU passthrough or anything of the sort, which could very well mean that functionality is very limited.

http://askubuntu.com/questions/139320/enable-graphics-card-in-virtualbox
https://superuser.com/questions/945740/passthrough-graphics-card-to-virtualbox

**Comment by ChristianGreiner** [comment]
@hsnabn Yes, I used VirtualBox.

**Comment by ilexp** [comment]
@ChristianGreiner Any news on this? If this is a VM issue / related to being below the minimum graphics API level, I'd close this. Nothing much to be done on the Duality side in that case.

**Comment by ChristianGreiner** [comment]
@ilexp No, there aren't any news. I can test this from tomorrow.

**Comment by ilexp** [comment]
Closing this as discussed in the chat. Without GPU access through the VM, there is no way for Duality to run properly. Software rendering is not sufficient.
