### ISSUE TITLE
Editor crashed on startup due to OpenTK-Exception

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#519]
### Summary

The editor is crashing every time when I'm starting Dualitor on my laptop.

### Specs

````
Summary
		Operating System
			Windows 10 Enterprise 2015 LTSB 64-bit
		CPU
			Intel Mobile Core 2 Duo T7300 @ 2.00GHz	68 °C
			Merom 65nm Technology
		Motherboard
			Hewlett-Packard 30BE (U10)
		Graphics
			Generic PnP Monitor (1440x900@60Hz)
			Intel Mobile Intel 965 Express Chipset Family (HP)
			Intel Mobile Intel 965 Express Chipset Family (HP)
		OpenGL
			Version: 1.1
Operating System
	Windows 10 Enterprise 2015 LTSB 64-bit
	Computer type: Notebook
		.NET Frameworks installed
			v4.6 Full
			v4.6 Client
			v3.5 SP1
			v3.0 SP2
			v2.0 SP2
````

OpenGL Report:

````
Renderer: GDI Generic
Vendor: Microsoft Corporation
Memory: 384 MB
Version: 1.1.0
Shading language version: N/A


Max texture size: 1024 x 1024
Max texture coordinates: 0
Max vertex texture image units: 0
Max texture image units: 0
Max geometry texture units: 0
Max anisotropic filtering value: 0
Max number of light sources: 8
Max viewport size: 16384 x 16384
Max uniform vertex components: 0
Max uniform fragment components: 0
Max geometry uniform components: 0
Max varying vectors: 0
Max samples: 0
Max draw buffers: 0


GL Extensions: 3
\i0 

GL_WIN_swap_hint
GL_EXT_paletted_texture
GL_EXT_bgra

Core features
v1.1 (100 % - 7/7)
v1.2 (12 % - 1/8)
v1.3 (0 % - 0/9)
v1.4 (0 % - 0/15)
v1.5 (0 % - 0/3)
v2.0 (0 % - 0/10)
v2.1 (0 % - 0/3)
v3.0 (0 % - 0/23)
v3.1 (0 % - 0/8)
v3.2 (0 % - 0/10)
v3.3 (0 % - 0/10)
v4.0 (0 % - 0/14)
v4.1 (0 % - 0/7)
v4.2 (0 % - 0/13)
v4.3 (0 % - 0/23)
v4.4 (0 % - 0/10)
v4.5 (0 % - 0/11)
vARB 2015 (0 % - 0/13)
vARB 2016 (0 % - 0/1)
OpenGL driver version check (Current: 1.1.0, Latest known: ):
 Latest version of display drivers found 
 According the database, you are running the latest display drivers for your video card.
 No ICD registry entry 
 The current OpenGL driver doesn't expose the SOFTWARE/Microsoft/Windows (NT)/CurrentVersion/OpenGLDrivers registry entry. Unable to detect the driver version, driver revision name and filename.
 No multitexturing support 
 This may cause performance loss in some applications.
 No secondary color support 
 Some applications may not render polygon highlights correctly.
 No S3TC compression support 
 This may cause performance loss in some applications.
 No texture edge clamp support 
 This feature adds clamping control to edge texel filtering. Some programs may not render textures correctly (black line on borders.)
 No vertex program support 
 This feature enables vertex programming (equivalent to DX8 Vertex Shader.) Some current or future OpenGL programs may require this feature.
 No fragment program support 
 This feature enables per pixel programming (equivalent to DX9 Pixel Shader.) Some current or future OpenGL programs may require this feature.
 No OpenGL Shading Language support 
 This may break compatibility for applications using per pixel shading.
 No Frame buffer object support 
 This may break compatibility for applications using render to texture functions.
 Few texture units found 
 This may slow down some applications using fragment programs or extensive texture mapping.
Extension verification: 
 GL_EXT_color_subtable  was not found, but has the entry point  glColorSubTableEXT  
````

### Attachments

Stacktrace:
````
Application: DualityEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at OpenTK.Graphics.OpenGL.GL+Ext.GenFramebuffers(Int32, Int32 ByRef)
   at Duality.Backend.DefaultOpenTK.NativeRenderTarget.Duality.Backend.INativeRenderTarget.Setup(System.Collections.Generic.IReadOnlyList`1<Duality.Backend.INativeTexture>, Duality.AAQuality)
   at Duality.Resources.RenderTarget.SetupNativeRes()
   at Duality.Resources.RenderTarget..ctor(Duality.AAQuality, Duality.ContentRef`1<Duality.Resources.Texture>[])
   at Duality.Components.Camera.SetupPickingRT(Duality.Point2)
   at Duality.Components.Camera.RenderPickingMap(Duality.Point2, Boolean)
   at Duality.Editor.Plugins.CamView.CamViewClient.RenderPickingMap()
   at Duality.Editor.Plugins.CamView.CamViewClient.PickRendererAt(Int32, Int32)
   at Duality.Editor.Plugins.CamView.CamViewStates.SceneEditorCamViewState.PickSelObjAt(Int32, Int32)
   at Duality.Editor.Plugins.CamView.CamViewStates.ObjectEditorCamViewState.UpdateMouseover(System.Drawing.Point)
   at Duality.Editor.Plugins.CamView.CamViewStates.ObjectEditorCamViewState.UpdateAction()
   at Duality.Editor.Plugins.CamView.CamViewStates.SceneEditorCamViewState.ApplyEditorSelection(Duality.Editor.ObjectSelection)
   at Duality.Editor.Plugins.CamView.CamView.SetCurrentState(Duality.Editor.Plugins.CamView.CamViewStates.CamViewState)
   at Duality.Editor.Plugins.CamView.CamView.OnShown(System.EventArgs)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at Duality.Editor.Program.Main(System.String[])
````

I can start and run the DualityLauncher without any problems.

**Comment by ChristianGreiner** [comment]
I just realized that this issue has resonances to my other issue (https://github.com/AdamsLair/duality/issues/516)

So probably the old OpenGL Version might be the problem.

**Comment by ilexp** [comment]
> Renderer: GDI Generic
Vendor: Microsoft Corporation
Memory: 384 MB
Version: 1.1.0

This is definitely an OpenGL issue. You're using a software renderer that is at OpenGL ~1.1. The minimum required OpenGL version is 2.1, plus some extensions. Closing this, because there's nothing much to be done - sorry about that. Duality just requires some of that stuff to work properly and GL 1.x can be safely considered legacy by now.

If you're on a laptop with an onboard and a "real" GPU, make sure that GPU is used when running Duality. Drivers try to auto-detect this, but lots of them won't recognize Duality and other OpenTK applications on their own.
