### ISSUE TITLE
Component-Inspector throws TargetInvocationException

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#522]
### Summary

The editor throws a TargetInvocationException when you click on the property "Type" to expand it.

![](http://i.imgur.com/hRFcaKX.png)

### What I did

I created a struct that has a property called "Type". The datatype is also "Type".
```C#
private Type type;
```

### Log

```
[Edit] Error:       TargetInvocationException: Exception has been thrown by the target of an invocation.
CallStack:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at AdamsLair.WinForms.PropertyEditing.MemberwisePropertyEditor.<>c__DisplayClass8.<ReflectTypeForMember>b__3(Object v) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\MemberwisePropertyEditor.cs:line 220
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at AdamsLair.WinForms.ReflectionHelper.GetCommonBaseClass(IEnumerable`1 types) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\Internal\ReflectionHelper.cs:line 55
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.ReflectDynamicType(Type staticType, IEnumerable`1 dynamicTypes) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 803
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.ReflectDynamicType(Type staticType, IEnumerable`1 values) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 789
   at AdamsLair.WinForms.PropertyEditing.MemberwisePropertyEditor.ReflectTypeForMember(MemberInfo member, IEnumerable`1 values) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\MemberwisePropertyEditor.cs:line 220
   at AdamsLair.WinForms.PropertyEditing.MemberwisePropertyEditor.AddEditorForMember(MemberInfo member, IEnumerable`1 values, PropertyEditor replaceOld) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\MemberwisePropertyEditor.cs:line 132
   at AdamsLair.WinForms.PropertyEditing.MemberwisePropertyEditor.InitContent() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\MemberwisePropertyEditor.cs:line 95
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.set_Expanded(Boolean value) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 63
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.IndentChildExpandOnMouseDown(MouseEventArgs e, GroupedPropertyEditor childGroup) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 647
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 762
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 752
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 752
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 752
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 752
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 752
   at AdamsLair.WinForms.PropertyEditing.GroupedPropertyEditor.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\GroupedPropertyEditor.cs:line 752
   at AdamsLair.WinForms.PropertyEditing.PropertyGrid.OnMouseDown(MouseEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyGrid.cs:line 718
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
````

Best regards!

**Comment by ilexp** [comment]
Can you share the source code for your property "Type"? A `TargetInvocationException` in this specific case likely means that there was an exception while invoking the getter method.

**Comment by ChristianGreiner** [comment]
Sure.

````C#
public struct TiledProperty
{
	public string Name
	{
		get { return name; }
	}

	public Type Type
	{
		get { return type; }
	}

	public object Value
	{
		get { return value; }
	}

	private string name;
	private Type type;
	private object value;

	public TiledProperty(string name, Type type, object value)
	{
		this.name = name;
		this.type = type;
		this.value = value;
	}
}
````

**Comment by ilexp** [comment]
Hm, okay - that looks pretty straightforward 😄 Must be something else then - I'll try to reproduce this.

**Comment by ilexp** [comment]
Potentially related issue after importing a file with a custom (Tiled tilemap) importer (reported by @ChristianGreiner as well): https://pastebin.com/1KQRSVSf

The callstack looks quite similar.

**Comment by ilexp** [comment]
Fixed. Release in progress. Check back for package updates in about 20 minutes.
