### ISSUE TITLE
Check for DivideByZeroException in SourceTileSize

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#563]
### Summary

The Editor throws a **DivideByZeroException** when you type "0" (without apostrophe) in the **SourceTileSize-Textbox**.

### How to reproduce

- Open **Tileset Editor**
- Select your Tileset
- Type "0" (Zero) in the **SourceTileSize-Textbox**
![image](https://user-images.githubusercontent.com/6233308/30128917-94ecb026-9344-11e7-9cbf-f1a5e7b6e5e9.png)

### Analysis

- Do a zero check [here](https://github.com/AdamsLair/duality/blob/7febba7196982e9fa7903a501378bf6e121157fe/Source/Plugins/Tilemaps/Core/Tilesets/TilesetRenderInput.cs#L151-L157)

#### Editor Log:
````
[Edit] Error:   DivideByZeroException: Attempted to divide by zero.
CallStack:
   at Duality.Plugins.Tilemaps.TilesetRenderInput.GetSourceTileCount(Int32 sourceImageWidth, Int32 sourceImageHeight) in c:\projects\duality\Source\Plugins\Tilemaps\Core\Tilesets\TilesetRenderInput.cs:line 154
   at Duality.Editor.Plugins.Tilemaps.TilesetView.OnTilesetChanged() in c:\projects\duality\Source\Plugins\Tilemaps\Editor\Modules\TilesetView.cs:line 773
   at Duality.Editor.Plugins.Tilemaps.TilesetView.DualityEditorApp_ObjectPropertyChanged(Object sender, ObjectPropertyChangedEventArgs e) in c:\projects\duality\Source\Plugins\Tilemaps\Editor\Modules\TilesetView.cs:line 1080
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Duality.Editor.DualityEditorApp.OnObjectPropertyChanged(Object sender, ObjectPropertyChangedEventArgs args) in c:\projects\duality\Source\Editor\DualityEditor\DualityEditorApp.cs:line 1217
   at Duality.Editor.Plugins.Tilemaps.TilesetEditorModes.VisualLayerTilesetEditorMode.OnTilesetModified(ObjectPropertyChangedEventArgs args) in c:\projects\duality\Source\Plugins\Tilemaps\Editor\TilesetEditorModes\VisualLayerTilesetEditorMode.cs:line 220
   at Duality.Editor.Plugins.Tilemaps.TilesetEditor.DualityEditorApp_ObjectPropertyChanged(Object sender, ObjectPropertyChangedEventArgs e) in c:\projects\duality\Source\Plugins\Tilemaps\Editor\Modules\TilesetEditor.cs:line 408
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Duality.Editor.DualityEditorApp.OnObjectPropertyChanged(Object sender, ObjectPropertyChangedEventArgs args) in c:\projects\duality\Source\Editor\DualityEditor\DualityEditorApp.cs:line 1217
   at Duality.Editor.UndoRedoActions.EditPropertyAction.Do() in c:\projects\duality\Source\Editor\DualityEditor\UndoRedoActions\EditPropertyAction.cs:line 100
   at Duality.Editor.Controls.DualitorPropertyGrid.EditorMemberPropertySetter(PropertyInfo property, IEnumerable`1 targetObjects, IEnumerable`1 values) in c:\projects\duality\Source\Editor\DualityEditor\Controls\DualitorPropertyGrid.cs:line 179
   at AdamsLair.WinForms.PropertyEditing.MemberwisePropertyEditor.<>c__DisplayClass2a.<CreatePropertyValueSetter>b__29(IEnumerable`1 values) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\MemberwisePropertyEditor.cs:line 485
   at AdamsLair.WinForms.PropertyEditing.PropertyEditor.SetValues(IEnumerable`1 objEnum) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditor.cs:line 463
   at Duality.Editor.Controls.PropertyEditors.VectorPropertyEditor.HandleValueEdited[T](Func`3 mergeOldNew) in c:\projects\duality\Source\Editor\DualityEditor\Controls\PropertyEditors\VectorPropertyEditor.cs:line 367
   at AdamsLair.WinForms.PropertyEditing.Templates.EditorTemplate.EmitEdited(Object value) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\EditorTemplate.cs:line 93
   at AdamsLair.WinForms.PropertyEditing.Templates.NumericEditorTemplate.stringEditor_Edited(Object sender, EventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\NumericEditorTemplate.cs:line 422
   at AdamsLair.WinForms.PropertyEditing.Templates.EditorTemplate.EmitEdited(Object value) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\EditorTemplate.cs:line 93
   at AdamsLair.WinForms.PropertyEditing.Templates.StringEditorTemplate.InsertText(String insertText) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\StringEditorTemplate.cs:line 133
   at AdamsLair.WinForms.PropertyEditing.Templates.StringEditorTemplate.OnKeyPress(KeyPressEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\StringEditorTemplate.cs:line 220
   at AdamsLair.WinForms.PropertyEditing.Templates.NumericEditorTemplate.OnKeyPress(KeyPressEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\NumericEditorTemplate.cs:line 228
   at AdamsLair.WinForms.PropertyEditing.PropertyGrid.OnKeyPress(KeyPressEventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyGrid.cs:line 910
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[Edit] Error:   DivideByZeroException: Attempted to divide by zero.
CallStack:
   at Duality.Plugins.Tilemaps.TilesetRenderInput.GetSourceTileCount(Int32 sourceImageWidth, Int32 sourceImageHeight) in c:\projects\duality\Source\Plugins\Tilemaps\Core\Tilesets\TilesetRenderInput.cs:line 154
   at Duality.Plugins.Tilemaps.Tileset.LookupTileSourceRect(Int32 renderConfigIndex, Int32 tileIndex, Point2& pos, Point2& size) in c:\projects\duality\Source\Plugins\Tilemaps\Core\Tilesets\Tileset.cs:line 194
   at Duality.Editor.Plugins.Tilemaps.TilesetView.OnPaintTiles(PaintEventArgs e) in c:\projects\duality\Source\Plugins\Tilemaps\Editor\Modules\TilesetView.cs:line 860
   at Duality.Editor.Plugins.Tilemaps.TilesetView.OnPaint(PaintEventArgs e) in c:\projects\duality\Source\Plugins\Tilemaps\Editor\Modules\TilesetView.cs:line 1021
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
````

**Comment by ilexp** [comment]
Fixed. Release in progress.
