### ISSUE TITLE
Fix Enum-Exception in EnumPropertyEditor

### ISSUE THREAD

**Issue by ChristianGreiner** [AdamsLair/duality#583]
### Summary
When you create an empty Enum class and try to select a value, the editor throws an exception.

### How to reproduce 

1. Create a empty Enum-Class.

```C#
public enum Keyframe
{
}
```

2. Create a public property of this Enum-Class
```C#
public Keyframe Keyframe { get; set; }
```

3. Try to select zero (0) in the property editor (Object inspector)

![image](https://user-images.githubusercontent.com/6233308/31588925-4147c1b2-b1f9-11e7-8379-6a9a2e1c2461.png)

![image](https://user-images.githubusercontent.com/6233308/31588933-53e3688a-b1f9-11e7-83e3-8da732046199.png)

### Analysis

- Handle empty Enums in the Enum property editor correctly.
https://github.com/AdamsLair/winforms/blob/master/WinForms/PropertyEditing/PropertyEditors/EnumPropertyEditor.cs

### Attachments

```
[Edit] Error:       NullReferenceException: Object reference not set to an instance of an object.
CallStack:
   at AdamsLair.WinForms.PropertyEditing.Editors.EnumPropertyEditor.stringSelector_Edited(Object sender, EventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\PropertyEditors\EnumPropertyEditor.cs:line 153
   at AdamsLair.WinForms.PropertyEditing.Templates.EditorTemplate.EmitEdited(Object value) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\EditorTemplate.cs:line 93
   at AdamsLair.WinForms.PropertyEditing.Templates.ComboBoxEditorTemplate.dropdown_AcceptSelection(Object sender, EventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\ComboBoxEditorTemplate.cs:line 244
   at AdamsLair.WinForms.PropertyEditing.Templates.ComboBoxDropDown.Accept() in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\ComboBoxDropDown.cs:line 36
   at AdamsLair.WinForms.PropertyEditing.Templates.ComboBoxDropDown.OnClick(EventArgs e) in c:\Stuff\svn\Projects\AdamsLair.WinForms\WinForms\PropertyEditing\EditorTemplates\ComboBoxDropDown.cs:line 53
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Barsonax** [comment]
Not something that will happen often but this shouldn't cause a exception. I will take a look tomorrow.

**Comment by Barsonax** [comment]
I think the fix is to replace this [line](Enum[] values = Enum.GetValues(EditedType).Cast<Enum>().ToArray();) with:
`
Enum[] values = Enum.GetValues(EditedType).Cast<Enum>().ToArray();
`

**Comment by ilexp** [comment]
### Progress

- Merged the WinForms PR by @Barsonax.

### Immediate ToDo

- Deploy a new NuGet package version for AdamsLair.WinForms.
- Update dependencies in Duality to the new package.

**Comment by ilexp** [comment]
### Progress

- Fixed the previously introduced bug.

### Immediate ToDo

- Deploy a new NuGet package version for AdamsLair.WinForms.
- Update dependencies in Duality to the new package.

**Comment by ilexp** [comment]
Done. Release in progress.
