### ISSUE TITLE
Tilemap goes over renderer vertex limit with large maps

### ISSUE THREAD

**Issue by Barsonax** [AdamsLair/duality#705]
### Summary

When you create a large tilemap it cannot be rendered due to going over the vertex limit. This bug was introduced in duality v3.

### How to reproduce

- Create a 320x200 tilemap
- See error spam

### Attachments

Stacktrace:
```
CoreError:   There was an error while RenderSetup "Default\RenderSetup\Default" was collecting renderer drawcalls: ArgumentException: This vertex batch storage limits batch size to a maximum of 65535 vertices. Cannot provide a vertex slice that is 190400 vertices long.
CallStack:
   at Duality.Drawing.VertexBatchStore.ThrowMaxSizeExceeded(Int32 requestedLength) in C:\projects\duality\Source\Core\Duality\Drawing\VertexData\VertexBatchStore.cs:line 192
   at Duality.Drawing.VertexBatchStore.Rent[T](Int32 length) in C:\projects\duality\Source\Core\Duality\Drawing\VertexData\VertexBatchStore.cs:line 107
   at Duality.Drawing.DrawDevice.AddVertices[T](BatchInfo material, VertexMode vertexMode, T[] vertexBuffer, Int32 vertexCount) in C:\projects\duality\Source\Core\Duality\Drawing\DrawDevice.cs:line 503
   at Duality.Drawing.ExtMethodsIDrawDevice.AddVertices[T](IDrawDevice device, ContentRef`1 material, VertexMode vertexMode, T[] vertexBuffer, Int32 vertexCount) in C:\projects\duality\Source\Core\Duality\Drawing\IDrawDevice.cs:line 232
   at Duality.Plugins.Tilemaps.TilemapRenderer.Draw(IDrawDevice device) in C:\projects\duality\Source\Plugins\Tilemaps\Core\Tilemaps\Components\TilemapRenderer.cs:line 397
   at Duality.Resources.RenderSetup.OnCollectRendererDrawcalls(DrawDevice drawDevice, RawList`1 visibleRenderers, Boolean renderersSortedByType) in C:\projects\duality\Source\Core\Duality\Resources\RenderSetup\RenderSetup.cs:line 522
   at Duality.Resources.RenderSetup.CollectRendererDrawcalls(Scene scene, DrawDevice drawDevice) in C:\projects\duality\Source\Core\Duality\Resources\RenderSetup\RenderSetup.cs:line 386
```

**Comment by ilexp** [comment]
A note on addressing this issue: 

- Duality v3 indexes vertices using `uint` values, so if there are more than 65535 vertices in a single batch, they cannot be addressed. This is by design to ensure compatibility and consistency across platforms that do not support bigger data types for index buffers, [such as GLES 2.0](http://docs.gl/es2/glDrawElements).
- The above safeguard is new in Duality v3, and it causes the issue in `TilemapRenderer`. It is, however, not the actual problem. The problem is `TilemapRenderer` not dealing with the limit accordingly.
- [Instead of submitting all vertices in a single batch](https://github.com/AdamsLair/duality/blob/7bad4c4e39fde8598d411cfa252e6f8a3d699601/Source/Plugins/Tilemaps/Core/Tilemaps/Components/TilemapRenderer.cs#L391), regardless of size, the `TilemapRenderer` should instead keep track of how many vertices are part of the current batch, and submit-and-restart if the limit would otherwise be exceeded. As a result, multiple smaller batches will be submitted, instead of a single one.

**Comment by ilexp** [comment]
Fixed and released. Should be out there in about 20 minutes.
