### ISSUE TITLE
Editor crash after installed.

### ISSUE THREAD

**Issue by Howld** [AdamsLair/duality#762]
### Summary

After installed, the editor open auto but crash with a few seconds.

### How to reproduce

Open DualityEditor.exe again.

### Attachments
<pre>
[Core] Msg: Assembly loaded: DualityPhysics 3.0.4.0
[Edit] ERR: NullReferenceException: Object reference not set to an instance of an object.
            CallStack:
               at Duality.Editor.Plugins.CamView.CamView.InitGLControl() in C:\projects\duality\Source\Plugins\EditorModules\CamView\Modules\CamView.cs:line 521
               at Duality.Editor.Plugins.CamView.CamView.OnShown(EventArgs e) in C:\projects\duality\Source\Plugins\EditorModules\CamView\Modules\CamView.cs:line 354
               at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
               at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
               at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
               at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
               at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
               at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
[Edit] ERR: NullReferenceException: Object reference not set to an instance of an object.
            CallStack:
               at Duality.Editor.Plugins.CamView.CamView.Duality.Editor.IHelpProvider.ProvideHoverHelp(Point localPos, Boolean& captured) in C:\projects\duality\Source\Plugins\EditorModules\CamView\Modules\CamView.cs:line 1596
               at Duality.Editor.HelpSystem.UpdateHelpStack() in C:\projects\duality\Source\Editor\DualityEditor\HelpSystem.cs:line 189
               at Duality.Editor.HelpSystem.DualityEditorApp_EventLoopIdling(Object sender, EventArgs e) in C:\projects\duality\Source\Editor\DualityEditor\HelpSystem.cs:line 225
               at Duality.Editor.DualityEditorApp.OnEventLoopIdling() in C:\projects\duality\Source\Editor\DualityEditor\DualityEditorApp.cs:line 1140
               at Duality.Editor.DualityEditorApp.Application_Idle(Object sender, EventArgs e) in C:\projects\duality\Source\Editor\DualityEditor\DualityEditorApp.cs:line 1286
               at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
               at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
               at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
               at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
               at Duality.Editor.Program.Main(String[] args) in C:\projects\duality\Source\Editor\DualityEditor\Program.cs:line 53
</pre>

**Comment by SirePi** [comment]
Could you post your logfile_editor.txt somewhere?

**Comment by Howld** [comment]
[logfile.txt](https://github.com/AdamsLair/duality/files/3804138/logfile.txt)
[logfile_editor.txt](https://github.com/AdamsLair/duality/files/3804139/logfile_editor.txt)

**Comment by SirePi** [comment]
It's strange.. your installation is failing to load the platform plugins, which in turn end up crashing the editor (which is "normal").
If you just installed Duality, maybe it's a case of a botched setup; your backend plugin version is 3.1.3.0 while it should be 3.2.0.0 - the plugin was recently (3 weeks ago) updated to allow to set the hardware cursor.

your logfile_editor.txt
```
[Core] Msg:   Plugins\DefaultOpenTKBackend.core.dll...
[Core] Msg:     Assembly loaded: DefaultOpenTKBackend.core 3.1.3.0
```
my log, after a fresh download
```
[Core] Msg:   Plugins\DefaultOpenTKBackend.core.dll...
[Core] Msg:     Assembly loaded: DefaultOpenTKBackend.core 3.2.0.0
```

I'd suggest you try again with a [fresh download](https://get.duality2d.net/); it should all be good then

**Comment by Howld** [comment]
I downloaded it from https://www.duality2d.net/, maybe official should update it. Anyway, thanks your help, it works!
